__author__ = "wongxy github:xiyaowong"
__all__ = [
    "bilibili",
    "changya",
    "douyin",
    "kugou",
    "kuwo",
    "lizhiFM",
    "music163",
    "pipigaoxiao",
    "quanminkge",
    "weibo",
    "zhihu_video",
    "weishi",
    "zuiyou_voice",
    "qqmusic",
    "qianqian",
    "sing5",
    "pipix",
    "qingshipin",
    "qutoutiao",
    "ku6",
    "lofter",
    "open163",
    "xinpianchang",
    "baidutieba",
    "kuaishou",
]
